output: build/output
collections_config:
  my_collection:
    path: docs/tutorial-basics
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  my_blog:
    path: blog
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_enabled_editors:
  - visual
  - content
  - data
collection_groups:
  - heading: Blogging
    collections:
      - my_collection
      - my_blog


main_content: 
_inputs:
  main_content:
    type: markdown
    options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      bulletedlist: true
      indent: true
      numberedlist: true
      outdent: true
      code: true
      embed: true
      horizontalrule: true
      image: true
      table: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      styles: /css/editor.css
      left: align-left
      center: align-center
      right: align-right
      justify: align-justify
      image_size_attributes: true

    
