output: build/output
collections_config:
  my_collection:
    path: docs/tutorial-basics
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  my_blog:
    path: blog
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_enabled_editors:
  - visual
  - content
  - data
collection_groups:
  - heading: Blogging
    collections:
      - my_collection
      - my_blog


