output: build/output
collections_config:
  my_collection:
    path: docs/tutorial-basics
    output: false
    disable_add: true
    disable_add_folder: true
    
  my_blog:
    path: blog
    output: false


collection_groups:
  - heading: Blogging
    collections:
      - my_collection
      - my_blog





    
