collections_config:
  posts:
    path: blog
    output: true
    url: /blog/[slug]/
    _enabled_editors:
      - content
  posts:
    path: docs
    output: true
    url: /[slug]/
    _enabled_editors:
      - content